---
services:
  portainer-ce:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    hostname: "portainer"
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data:/data"
    restart: "unless-stopped"
