---
version: "3.9"
services:
  portainer-ce:
    image: portainer/portainer-ce:latest
    container_name: portainer
    hostname: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    networks:
      - portainer
    restart: unless-stopped
networks:
  portainer:
    name: portainer
    ipam:
      config:
        - subnet: "172.16.3.0/24"
          gateway: "172.16.3.1"
